networks:
  react:
    internal: true
  traefik:
    external: true

services:
  react-docker:
    container_name: react-docker
    build:
      context: ./react-docker
    ports:
      - "3000:3000"
    networks:
      - react
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.dashboard.rule=Host(`dashboard.assomayday.org`)
      - traefik.http.routers.dashboard.tls.certresolver=letsencrypt
      - traefik.http.services.dashboard.loadbalancer.server.port=3000
      - traefik.docker.network=traefik 
